# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

array = [1,2]
evenSums = 2

x = 0
y = 1

until (array[x] + array[y]) > 4000000
	array.push(array[x] + array[y])
	if (array[x] + array[y]) % 2 == 0
		evenSums += (array[x] + array[y])
	end
	x += 1
	y += 1
end

puts evenSums
# [ Loop index 0,1 - add - push - increment by one, continue until 4000000 ]
